site_name: SIL-Aadhar
locale: en
theme:
    name: mkdocs
    color_mode: auto
    user_color_mode_toggle: True
    logo: img/shreetron.png
    features:
        - content.code.copy
        - content.code.select
nav:
    - index.md
    - about.md
    - Help.md